2124802010277_LeTuanKiet_CuoiKy/Controllers/GrammarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _2124802010277_LeTuanKiet_CuoiKy.Models;
namespace _2124802010277_LeTuanKiet_CuoiKy.Controllers
{
    public class GrammarController : Controller
    {
        DataTiengAnhEntities db = new DataTiengAnhEntities();
        public List<NguPhap> FilterG(int op)
        {
            NguoiDung nd = (NguoiDung)Session["TaiKhoan"];
            List<NguPhap> tmp = db.NguPhaps.Where(item => item.TrangThai == true).ToList();
            if(op==1)
            {
                tmp = db.NguPhaps.OrderByDescending(item => item.NgayDang).Where(item => item.TrangThai == true).ToList();
            }    
            else if(op==2)
            {
                tmp = db.NguPhaps.OrderBy(item => item.NgayDang).Where(item => item.TrangThai == true).ToList();
            }  
            else if(op==3)
            {
                tmp = db.NguPhaps.OrderByDescending(item => item.LuotXem).Where(item => item.TrangThai == true).ToList();
            }  
            else if(op==4)
            {
                tmp = db.NguPhaps.OrderBy(item => item.LuotXem).Where(item => item.TrangThai == true).ToList();
            }    
            else if(op==5)
            {
                if(nd!=null)
                {
                    tmp = db.NguPhaps.Where(item => item.IdTacGia == nd.MaKH).ToList();
                }    
            }    
            return tmp;
        }
        // GET: Grammar
        public ActionResult Index(string KeyWork, int pg = 1,int fillter=0)
        {
            List<NguPhap> tmp = db.NguPhaps.Where(item => item.TrangThai == true).ToList();

            if(fillter!=0)
            {
                tmp = FilterG(fillter);
            }    

            if (!string.IsNullOrEmpty(KeyWork))
            {
                tmp = db.NguPhaps.Where(item => item.TrangThai==true && (item.TenNguPhap.Contains(KeyWork) || db.NguoiDungs.FirstOrDefault(x=>x.MaKH==item.IdTacGia).HoTenKH.Contains(KeyWork))).ToList();
            }    
            const int PageSize = 9;
            if(pg<1)
            {
                pg = 1;
            }
            int totalPage = tmp.Count();
            Pager p = new Pager(totalPage,pg,PageSize);
            int skipPage = (pg - 1) * PageSize;
            List<NguPhap> tmp1 = tmp.Skip(skipPage).Take(PageSize).ToList();
            if (fillter==0)
            {
                tmp1 = tmp.OrderBy(item => item.IdNguPhap).Skip(skipPage).Take(PageSize).ToList();
            }    
            ViewBag.Pager = p;
            ViewBag.fillter = fillter;
            ViewBag.TaiKhoan = db.NguoiDungs.ToList();
            if (TempData["ThongBaoThem"] != null)
                ViewBag.ThongBaoThem = TempData["ThongBaoThem"];
            return View(tmp1);
        }

        /*xử lý khi thêm 1 ngữ pháp mới start*/ 
        public ActionResult AddGrammar()
        {
            if (Session["TaiKhoan"] == null)
                return RedirectToAction("DangNhap", "User");
            return View();
        }

        public string Truncate(string s, int length)
        {
            if (s.Length < length)
            {
                return s;
            }
            else
            {
                return s.Substring(0, length);
            }
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddGrammar(FormCollection data)
        {
            NguPhap np = new NguPhap();

            var sIdTacGia = (NguoiDung)Session["TaiKhoan"];
            var sTen = data["TenNguPhap"];
            var sNoiDung = data["NoiDung"];
            var sMoTa = data["MoTa"];

            np.IdTacGia = sIdTacGia.MaKH;
            np.TenNguPhap = Truncate(sTen,100);
            np.NoiDung = sNoiDung;
            np.MoTaNgan = sMoTa;
            np.LuotXem = 0;
            np.LuotThich = 0;
            np.NgayDang = DateTime.Now;
            if (sIdTacGia.Admin == true)
                np.TrangThai = true;
            else
                np.TrangThai = false;
            db.NguPhaps.Add(np);
            db.SaveChanges();
            TempData["ThongBaoThem"] = "We have recorded your document, please wait for moderation for a few minutes";
            return RedirectToAction("Index");
        }
        /*Xử lý khi thêm 1 ngữ pháp mới kết thúc*/

        /*Chi tiết 1 ngữ pháp start*/
        public ActionResult DetailGrammar(int id)
        {
            NguPhap tmp = db.NguPhaps.FirstOrDefault(item => item.IdNguPhap == id);  
            return View(tmp);
        }
        public ActionResult MucLuc()
        {
            List<NguPhap> tmp = db.NguPhaps.Where(item=> item.TrangThai==true).ToList();
            return PartialView(tmp);
        }
        
        public ActionResult IncreaseView(int id)
        {
            NguPhap tmp = db.NguPhaps.FirstOrDefault(item => item.IdNguPhap == id);
            if (tmp != null)
            {
                tmp.LuotXem += 1;
                db.SaveChanges();
            }
            return RedirectToAction("DetailGrammar",new { id=id});
        }
        /*Chi tiết 1 ngữ pháp end*/
    }
}

2124802010277_LeTuanKiet_CuoiKy/Views/Grammar/AddGrammar.cshtml
@{
    ViewBag.Title = "AddGrammar";
}
<div class="ContrainerAddGrammar"
     style="
        padding: 50px 30px 50px 30px;
    ">
    <form action="@Url.Action("AddGrammar","Grammar")" method="post">
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Tên ngữ pháp</label>
            <input name="TenNguPhap" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nhập tên loại kiến thức bạn muốn chia sẻ">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Mô tả ngắn gọn</label>
            <textarea name="MoTa" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Mô tả ngắn gọn kiến thức bạn muốn nói khoảng 40 chữ cái"></textarea>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Nội dung</label>
            <textarea name="NoiDung" class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Nhập nội dung"></textarea>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-3">Gửi</button>
        </div>
    </form>
</div>
@section scripts{
    <script>
        CKEDITOR.replace("NoiDung");
    </script>
}

2124802010277_LeTuanKiet_CuoiKy/Views/Grammar/DetailGrammar.cshtml
@model _2124802010277_LeTuanKiet_CuoiKy.Models.NguPhap
@{
    ViewBag.Title = "DetailGrammar";
    List<_2124802010277_LeTuanKiet_CuoiKy.Models.NguPhap> MucLuc = ViewBag.MucLuc;
}
<div class="ContainerDetailGrammar">
    <div id="navigation" style="margin-right: 10px">
        <p style="text-align: center"><strong>Mục lục</strong></p>
        @Html.Action("MucLuc", "Grammar")
    </div>
    <div id="extra">
        @Html.Raw(Model.NoiDung)
    </div>
</div>

<script>
    $(document).ready(function () {
        var ul = $('#navigation ul');
        ul.scrollTop(ul[0].scrollHeight);
    });
</script>

2124802010277_LeTuanKiet_CuoiKy/Views/Grammar/Index.cshtml
@model List<_2124802010277_LeTuanKiet_CuoiKy.Models.NguPhap>
@using _2124802010277_LeTuanKiet_CuoiKy.Models
@{
    ViewBag.Title = "Index";
    List<_2124802010277_LeTuanKiet_CuoiKy.Models.NguoiDung> TaiKhoan = ViewBag.TaiKhoan;
    _2124802010277_LeTuanKiet_CuoiKy.Models.NguoiDung x = new _2124802010277_LeTuanKiet_CuoiKy.Models.NguoiDung();
    int fillter = (int)ViewBag.fillter;
    Pager p = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        p = ViewBag.Pager;
        pageNo = p.CurrentPage;
    }

    string op = fillter == 0 ? "selected" : "";
    string op1 = fillter == 1 ? "selected" : "";
    string op2 = fillter == 2 ? "selected" : "";
    string op3 = fillter == 3 ? "selected" : "";
    string op4 = fillter == 4 ? "selected" : "";
    string op5 = fillter == 5 ? "selected" : "";
}
<div class="ContainerGrammar">
    <div style="display: flex; flex-direction: row-reverse; margin-bottom: 15px">
        <a href="~/Grammar/AddGrammar" class="btn btn-outline-primary" style="margin-left: 20px; height: 45px; display: flex; align-items: center; justify-content: center">
            Thêm tài liệu
        </a>
        <select class="btn btn-outline-primary" aria-label="Default select example" style="width: 10%; margin-left: 10px" onchange="filter(this.value)">
            <option value="0" @op>Tất cả</option>
            <option value="1" @op1>Mới nhất</option>
            <option value="2" @op2>Cũ nhất</option>
            <option value="3" @op3>Nhiều lượt xem</option>
            <option value="4" @op4>Ít lượt xem</option>
            <option value="5" @op5>Bài đăng của tôi</option>
        </select>
        <form class="input-group" style="display: flex; flex-direction: row-reverse">
            <button type="submit" class="btn btn-outline-primary" data-mdb-ripple-init
                    style="height: 45px; border-radius: 5px">
                search
            </button>
            <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" name="KeyWork" style="max-width: 30%" />
        </form>
    </div>
    <div class="List-card" style="padding-left: 5%">
        <div class="container mt-5 mb-3">
            <div class="row">
                @foreach (var item in Model)
                {
                    x = TaiKhoan.FirstOrDefault(n => n.MaKH == item.IdTacGia);
                    if (x.HinhDaiDien == null)
                    {
                        x.HinhDaiDien = "~/images/logo.png";
                    }
                    <div class="col-md-4" style="margin-bottom: 15px;">
                        <a href="@Url.Action("IncreaseView","Grammar", new { id =item.IdNguPhap})">
                            <div class="card p-3 mb-2">
                                <div class="d-flex justify-content-between">
                                    <div class="d-flex flex-row align-items-center">
                                        <div class="icon">
                                            <img src="@x.HinhDaiDien" style="min-width: 50px; max-width: 50px; min-height: 50px; max-height: 50px; border-radius: 15px">
                                        </div>
                                        <div class="ms-2 c-details">
                                            <h6 class="mb-0"> @x.HoTenKH</h6>
                                            <span>@item.NgayDang</span>
                                        </div>
                                    </div>
                                    <div class="badge"> <span>Tác giả</span> </div>
                                </div>
                                <p class="SmailDetail">
                                    @item.MoTaNgan
                                </p>
                                <div class="mt-5">
                                    <h3 class="heading" style="font-weight: bold;">@item.TenNguPhap</h3>
                                    <div class="mt-5">
                                        <div class="mt-3"> <span class="text1">@item.LuotXem lượt xem <span class="text2">@item.LuotThich lượt thích</span></span> </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<div class="container1">
    <ul class="pagination" style="justify-content: center">
        @for (int i = p.StartPage; i <= p.EndPage; i++)
        {
            <li class="page-item @(i==p.CurrentPage ? "active" : "")">
                <a class="page-link" href="~/Grammar/Index?pg=@i&fillter=@fillter">@i</a>
            </li>
        }
    </ul>
</div>
@section scripts{
    <script>
        var ThongBaoThem = '@ViewBag.ThongBaoThem';
        if (ThongBaoThem != "")
            alert(ThongBaoThem);

        function filter(Op) {
            console.log(Op);
            window.location.href = "/Grammar/Index?fillter=" + Op + "";
        }
    </script>
}

2124802010277_LeTuanKiet_CuoiKy/Views/Grammar/MucLuc.cshtml
@model IEnumerable<_2124802010277_LeTuanKiet_CuoiKy.Models.NguPhap>
<ul class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("IncreaseView","Grammar", new { id =item.IdNguPhap})" style="color: white">
            <li class="list-group-item active">
                @item.TenNguPhap

            </li>
        </a>
    }
</ul>