2124802010277_LeTuanKiet_CuoiKy/Areas/Admin/Controllers/ManagerExamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _2124802010277_LeTuanKiet_CuoiKy.App_Start;
using _2124802010277_LeTuanKiet_CuoiKy.Models;
namespace _2124802010277_LeTuanKiet_CuoiKy.Areas.Admin.Controllers
{
    public class ManagerExamsController : Controller
    {
        // GET: Admin/ManagerExams
        DataTiengAnhEntities db = new DataTiengAnhEntities();
        [AdminAuthorize()]
        public ActionResult Index(string KeyWork,int pg=1)
        {
            const int pageSize = 10;
            if (pg < 1)
                pg = 1;
            if (!string.IsNullOrEmpty(KeyWork))
            {
                List<KyThi> tmp1 = db.KyThis.OrderByDescending(item => item.NgayKetThuc).Where(item=> item.IdKyThi.Contains(KeyWork) || item.TenKyThi.Contains(KeyWork)).ToList();
                int totalitem1 = tmp1.Count();
                var pager1 = new Pager(totalitem1, pg, pageSize);
                int skipPage1 = (pg - 1) * pageSize;
                ViewBag.Pager = pager1;
                ViewBag.pg = pg;
                return View(tmp1);
            }    
            List<KyThi> tmp = db.KyThis.OrderByDescending(item => item.NgayKetThuc).ToList();
            int totalitem = tmp.Count();
            var pager = new Pager(totalitem, pg, pageSize);
            int skipPage = (pg - 1) * pageSize;
            ViewBag.Pager = pager;
            ViewBag.pg = pg;
            List<KyThi> tmp2 = tmp.Skip(skipPage).Take(pageSize).ToList();
            return View(tmp2);
        }
        [AdminAuthorize()]
        public ActionResult CreateExams()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateExams(FormCollection data, List<CauHoi> LQuestion)
        {
            //Thêm kỳ thi start
            //Ngày thi
            DateTime tmp = DateTime.Parse(data["Ngay"]);
            tmp = tmp.AddHours(Convert.ToInt32(data["Hour"]));
            tmp = tmp.AddMinutes(Convert.ToInt32(data["Minute"]));

            //Ngày kết thúc
            DateTime tmp1 = DateTime.Parse(data["NgayKetThuc"]);
            tmp1 = tmp1.AddHours(Convert.ToInt32(data["HourEnd"]));
            tmp1 = tmp1.AddMinutes(Convert.ToInt32(data["MinuteEnd"]));


            KyThi newExam = new KyThi();
            newExam.IdKyThi = data["IdKyThi"];
            newExam.TenKyThi = data["TenKyThi"];
            newExam.Ngay = tmp;
            newExam.NgayKetThuc = tmp1;
            newExam.SoThiSinh = 0;
            newExam.TinhTrang = false;
            db.KyThis.Add(newExam);

            var Ckythi = db.KyThis.FirstOrDefault(item => item.IdKyThi == newExam.IdKyThi);
            if(tmp==null || string.IsNullOrEmpty(newExam.IdKyThi) || Ckythi!=null || tmp1==null)
            {
                return RedirectToAction("Fail");
            }    

            db.SaveChanges();
            //Thêm kỳ thi end

            //Thêm các câu hỏi của kỳ thi start
            foreach (var item in LQuestion)
            {

                CauHoi Q = new CauHoi();
                Q.IdBoCauHoi = data["IdKyThi"];
                Q.TenCauHoi = item.TenCauHoi;
                Q.DapAnA = item.DapAnA;
                Q.DapAnB = item.DapAnB;
                Q.DapAnC = item.DapAnC;
                Q.DapAnD = item.DapAnD;
                Q.DapAnDung = item.DapAnDung;
                db.CauHois.Add(Q);

            }
            db.SaveChanges();

            //Thêm các câu hỏi của kỳ thi end

            Session["IdKyThi"] = data["IdKyThi"];
            return RedirectToAction("Index");
        }
        [AdminAuthorize()]
        public ActionResult DetailExams(string id)
        {
            KyThi tmp = db.KyThis.FirstOrDefault(item => item.IdKyThi == id);
            List<ChiTietThiSinh> ts = db.ChiTietThiSinhs.Where(item => item.IdKyThi == id).ToList();
            ViewBag.ThiSinh = ts;
            return View(tmp);
        }
        [AdminAuthorize()]
        public ActionResult CongBo(string id)
        {
            KyThi tmp = db.KyThis.FirstOrDefault(item => item.IdKyThi == id);
            List<ChiTietThiSinh> ts = db.ChiTietThiSinhs.Where(item => item.IdKyThi == id).ToList();

            tmp.TinhTrang = true;
            foreach (var item in ts)
            {
                NguoiDung nd = db.NguoiDungs.FirstOrDefault(it => it.MaKH == item.IdThiSinh);
                nd.DiemKyThi += item.Diem;
            }
            db.SaveChanges();
            foreach (var item in ts)
            {
                NguoiDung nd = db.NguoiDungs.FirstOrDefault(it => it.MaKH == item.IdThiSinh);
                List<CauHoi> ch = db.CauHois.Where(it => it.IdBoCauHoi == tmp.IdKyThi).ToList();

                string contentCustomer = System.IO.File.ReadAllText(Server.MapPath("~/Content/Temple/send2.html"));
                contentCustomer = contentCustomer.Replace("{{TenKyThi}}", tmp.TenKyThi);
                contentCustomer = contentCustomer.Replace("{{TenNd}}", nd.HoTenKH);
                contentCustomer = contentCustomer.Replace("{{IdKyThi}}", tmp.IdKyThi);
                contentCustomer = contentCustomer.Replace("{{NgayThi}}", tmp.Ngay.Value.ToString());
                contentCustomer = contentCustomer.Replace("{{Diem}}", item.Diem.ToString());
                contentCustomer = contentCustomer.Replace("{{Dung}}", item.Dung.ToString());
                contentCustomer = contentCustomer.Replace("{{Sai}}", item.Sai.ToString());
                contentCustomer = contentCustomer.Replace("{{ChuaLam}}", item.ChuaLam.ToString());
                contentCustomer = contentCustomer.Replace("{{NgayKetThuc}}", tmp.NgayKetThuc.ToString());
                contentCustomer = contentCustomer.Replace("{{SoCauHoi}}", ch.Count.ToString());
                WebBanHangOnline.Common.Common.SendMail("Admin Hoc Tieng Anh KL", "Kết quả kỳ thi " + tmp.IdKyThi, contentCustomer.ToString(), nd.Email);

            }
            return RedirectToAction("Index");
        }
        [AdminAuthorize()]
        public ActionResult DeleteExams(string id)
        {
            List<CauHoi> ch = db.CauHois.Where(item => item.IdBoCauHoi == id).ToList();
            List<ChiTietThiSinh> ts = db.ChiTietThiSinhs.Where(item => item.IdKyThi == id).ToList();
            KyThi kt = db.KyThis.FirstOrDefault(item => item.IdKyThi == id);
            foreach (var item in ch)
            {
                db.CauHois.Remove(item);
            }
            foreach (var item in ts)
            {
                db.ChiTietThiSinhs.Remove(item);
            }
            db.KyThis.Remove(kt);
            db.SaveChanges();


            return RedirectToAction("Index");
        }
        [AdminAuthorize()]
        public ActionResult EditExams(string id)
        {
            KyThi kt = db.KyThis.FirstOrDefault(item => item.IdKyThi == id);
            List<CauHoi> tmp = db.CauHois.Where(item => item.IdBoCauHoi == id).ToList();
            ViewBag.DanhSachCauHoi = tmp;
            return View(kt);
        }
        [AdminAuthorize()]
        [HttpPost] 
        public ActionResult EditExams(FormCollection f,List<CauHoi> LQuestion)
        {
            string IdKyThi = f["IdKyThi"];
            string TenKyThi = f["TenKyThi"];
            DateTime Ngay = DateTime.Parse(f["Ngay"]);
            Ngay = Ngay.AddHours(Convert.ToInt32(f["Hour"]));
            Ngay = Ngay.AddMinutes(Convert.ToInt32(f["Minute"]));

            DateTime NgayKt = DateTime.Parse(f["NgayKetThuc"]);
            NgayKt = NgayKt.AddHours(Convert.ToInt32(f["HourEnd"]));
            NgayKt = NgayKt.AddMinutes(Convert.ToInt32(f["MinuteEnd"]));

            Boolean TinhTrang = Boolean.Parse(f["TinhTrang"]);

            KyThi kt = db.KyThis.FirstOrDefault(item => item.IdKyThi == IdKyThi);
            kt.TenKyThi = TenKyThi;
            kt.Ngay = Ngay;
            kt.NgayKetThuc = NgayKt;

            kt.CauHois.Clear();
            List<CauHoi> lq = LQuestion.Where(item => item.TenCauHoi!=null && item.DapAnA!=null && item.DapAnB!=null && item.DapAnC!=null && item.DapAnD!=null && item.DapAnDung!=null ).ToList();
            foreach(var item in lq)
            {
                item.IdBoCauHoi = IdKyThi;
            }    
            kt.CauHois = lq;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        /*Quản lý kì thi end*/

        public ActionResult Fail()
        {
            return View();
        }
    }
}

2124802010277_LeTuanKiet_CuoiKy/Areas/Admin/Views/ManagerExams/CreateExams.cshtml
@model _2124802010277_LeTuanKiet_CuoiKy.Models.KyThi
@{
    ViewBag.Title = "CreateExams";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var i = 0;
}
<link rel="stylesheet" href="~/css/CreateExam.css" />
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Tạo Kỳ thi</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">
                        <li><a href="#" class="fw-normal"></a></li>
                    </ol>
                    <a href="@Url.Action("Index","ManagerExams")"
                       class="btn btn-danger  d-none d-md-block pull-right ms-3 hidden-xs hidden-sm waves-effect waves-light text-white">
                        Danh Sách các kỳ thi
                    </a>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        @*Xây dựng nội dung ở đây*@

        <div class="ContainerCreateExam">
            <form action="~/Admin/ManagerExams/CreateExams" method="post" onsubmit="return checkQuestion()">
                <div class="form-horizontal">
                    <h4>Thêm kỳ thi</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label class="control-label col-md-2">Id Kỳ thi</label>
                        <div class="col-md-10">
                            <input type="text" name="IdKyThi" class="IdKyThi" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-2">Tên kỳ thi</label>
                        <div class="col-md-10">
                            <input type="text" name="TenKyThi" class="NameKyThi" />
                        </div>
                    </div>
                    @*Ngày thi*@
                    <div style="border: 2px solid; padding: 20px; border-radius: 5px; margin-bottom: 10px ">
                        <div class="form-group">
                            <label class="control-label col-md-2">Ngày thi</label>
                            <div class="col-md-10">
                                <input type="date" id="ngay" name="Ngay" class="NgayKyThi">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="content">
                                <div class="column">
                                    <select name="Hour">
                                        <option value="Hour" selected disabled hidden>Hour</option>
                                    </select>
                                </div>
                                <div class="column">
                                    <select name="Minute">
                                        <option value="Minute" selected disabled hidden>Minute</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    @*Ngày Kết thúc*@
                    <div style="border: 2px solid; padding: 20px; border-radius: 5px ">
                        <div class="form-group">
                            <label class="control-label col-md-2">Ngày kết thúc</label>
                            <div class="col-md-10">
                                <input type="date" id="ngay" name="NgayKetThuc" class="NgayKyThi">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="content">
                                <div class="column">
                                    <select name="HourEnd">
                                        <option value="Hour" selected disabled hidden>Hour</option>
                                    </select>
                                </div>
                                <div class="column">
                                    <select name="MinuteEnd">
                                        <option value="Minute" selected disabled hidden>Minute</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div id="Exams">
                        <div id="Exam">
                            <div class="form-group" style="display: flex; flex-direction: row; align-items: center; justify-content: center;">
                                <div class="contenQ">
                                    <label class="control-label col-md-12">Câu hỏi: </label>
                                </div>
                                <div class="col-md-10" style="background-color: white;">
                                    <input class="form-control" name="LQuestion[@i].TenCauHoi" />
                                </div>
                            </div>

                            <div class="form-group" style="display: flex; flex-direction: row; align-items: center; justify-content: center;">
                                <div class="contenQ">
                                    <label class="control-label col-md-12">Đáp án A: </label>
                                </div>
                                <div class="col-md-10" style="background-color: white;">
                                    <input class="form-control" name="LQuestion[@i].DapAnA" />
                                </div>
                            </div>

                            <div class="form-group" style="display: flex; flex-direction: row; align-items: center; justify-content: center;">
                                <div class="contenQ">
                                    <label class="control-label col-md-12">Đáp án B: </label>
                                </div>
                                <div class="col-md-10" style="background-color: white;">
                                    <input class="form-control" name="LQuestion[@i].DapAnB" />
                                </div>
                            </div>

                            <div class="form-group" style="display: flex; flex-direction: row; align-items: center; justify-content: center;">
                                <div class="contenQ">
                                    <label class="control-label col-md-12">Đáp án C: </label>
                                </div>
                                <div class="col-md-10" style="background-color: white;">
                                    <input class="form-control" name="LQuestion[@i].DapAnC" />
                                </div>
                            </div>

                            <div class="form-group" style="display: flex; flex-direction: row; align-items: center; justify-content: center;">
                                <div class="contenQ">
                                    <label class="control-label col-md-12">Đáp án D: </label>
                                </div>
                                <div class="col-md-10" style="background-color: white;">
                                    <input class="form-control" name="LQuestion[@i].DapAnD" />
                                </div>
                            </div>

                            <div class="form-group" style="display: flex; flex-direction: row; align-items: center; justify-content: center;">
                                <div class="contenQ">
                                    <label class="control-label col-md-12">Đáp án đúng: </label>
                                </div>
                                <div class="col-md-10" style="background-color: white;">
                                    <input class="form-control" name="LQuestion[@i].DapAnDung" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div style="margin-top: 10px">
                        <button type="submit" class="btn btn-primary">Tạo kỳ thi</button>
                    </div>
                </div>
            </form>
            <button class="btn btn-primary" onclick="ThemCauHoi()" style="float: right">Thêm câu hỏi</button>
        </div>

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>


@section Script{
    <script>
        var i = 0;
        const currentTime = document.querySelector("h1"),
            content = document.querySelector(".content"),
            selectMenu = document.querySelectorAll("select"),
            setAlarmBtn = document.querySelector("button");
        for (let i = 24; i > 0; i--) {
            i = i < 10 ? `0${i}` : i;
            let option = `<option value="${i}">${i}</option>`;
            selectMenu[0].firstElementChild.insertAdjacentHTML("afterend", option);
            selectMenu[2].firstElementChild.insertAdjacentHTML("afterend", option);
        }

        for (let i = 59; i >= 0; i--) {
            i = i < 10 ? `0${i}` : i;
            let option = `<option value="${i}">${i}</option>`;
            selectMenu[1].firstElementChild.insertAdjacentHTML("afterend", option);
            selectMenu[3].firstElementChild.insertAdjacentHTML("afterend", option);
        }
        function ThemCauHoi() {

            i += 1; // Tăng giá trị i lên 1

            console.log("i sau khi tăng lên 1: " + i);

            var examsForm = document.getElementById('Exams');
            var examClone = document.getElementById('Exam').cloneNode(true);
            var inputFields = examClone.getElementsByTagName('input');

            // Cập nhật name của trường input để chứa giá trị mới của i
            for (var j = 0; j < inputFields.length; j++) {
                inputFields[j].name = "LQuestion[" + i + "]." + inputFields[j].name.split(".")[1];
                inputFields[j].value = '';
            }

            // Thêm bản sao vào Exams
            examsForm.appendChild(examClone);
        }


        function checkOption(idQ) {
            var Ques = document.querySelectorAll('#Exam');
            var opA = Ques[idQ].querySelector("[name$='.DapAnA']").value;
            var opB = Ques[idQ].querySelector("[name$='.DapAnB']").value;
            var opC = Ques[idQ].querySelector("[name$='.DapAnC']").value;
            var opD = Ques[idQ].querySelector("[name$='.DapAnD']").value;
            var correctAnswer = Ques[idQ].querySelector("[name$='.DapAnDung']").value;
            if (opA != correctAnswer && opB != correctAnswer && opC != correctAnswer && opD != correctAnswer) {
                alert("Có câu hỏi chưa hợp lệ");
                return false;
            }
            return true;
        }
        function checkQuestion() {
            var Ques = document.querySelectorAll('#Exam');
            for (let i = 0; i < Ques.length; i++) {
                if (checkOption(i) == false) {
                    console.log("ncc");
                    return false;
                }    
            }
            return true;
        }
        
        //checkQuestion();
    </script>
}

2124802010277_LeTuanKiet_CuoiKy/Areas/Admin/Views/ManagerExams/DetailExams.cshtml
@model _2124802010277_LeTuanKiet_CuoiKy.Models.KyThi
@using _2124802010277_LeTuanKiet_CuoiKy.Models
@{
    ViewBag.Title = "DetailExams";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    List<ChiTietThiSinh> ThiSinh = ViewBag.ThiSinh;
}

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Chi tiết kỳ thi @Model.IdKyThi</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">
                        <li><a href="#" class="fw-normal"></a></li>
                    </ol>
                    <a href="https://www.wrappixel.com/templates/ampleadmin/" target="_blank"
                       class="btn btn-danger  d-none d-md-block pull-right ms-3 hidden-xs hidden-sm waves-effect waves-light text-white">
                        Danh sách
                    </a>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        @*Xây dựng nội dung ở đây*@
        <h2>DetailExams</h2>

        <div>
            <h4>KyThi</h4>
            <hr />
            <table class="table">
                <thead class="table-dark">
                    <tr>
                        <th style="color: white">Tên kỳ thi</th>
                        <th style="text-align: center; color: white">Số thí sinh</th>
                        <th style="text-align: center; color: white">Ngày bắt đầu</th>
                        <th style="text-align: center; color: white">Ngày kết thúc</th>
                        <th style="text-align: center; color: white">Tình trạng công bố</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.TenKyThi</td>
                        <td style="text-align: center">@Model.SoThiSinh</td>
                        <td class="DetailExams" style="text-align: center">@string.Format("{0:dd/MM/yyyy}", Model.Ngay)</td>
                        <td class="DetailExams" style="text-align: center">@string.Format("{0:dd/MM/yyyy}", Model.Ngay)</td>
                        <td style="text-align: center">@Model.TinhTrang</td>
                    </tr>
                </tbody>
            </table>

            <p style="font-weight: bold; font-size: 20px">
                Chi tiết các thí sinh
            </p>
            <table class="table">
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Điểm
                    </th>
                    <th>
                        Số câu đúng
                    </th>
                    <th>
                        Số câu sai
                    </th>
                    <th>
                        Số câu chưa làm
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in ThiSinh)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.IdThiSinh)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Diem)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Dung)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Sai)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ChuaLam)
                        </td>
                        <td>
                        </td>
                    </tr>
                }
            </table>
            @if (Model.TinhTrang == false)
            {
                <div style="float: right">
                    <a class="btn btn-primary" href="@Url.Action("CongBo","ManagerExams",new { id=Model.IdKyThi})">Công bố</a>
                </div>
            }

        </div>
    </div>

2124802010277_LeTuanKiet_CuoiKy/Areas/Admin/Views/ManagerExams/Fail.cshtml
@{
    ViewBag.Title = "Fail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Danh Sách các kỳ thi</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex" style="align-items: center">

                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">

        <h1 style="color: red; text-align: center">Xử lý thất bại vui lòng thử lại</h1>

    </div>
</div>