2124802010277_LeTuanKiet_CuoiKy/Controllers/AssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _2124802010277_LeTuanKiet_CuoiKy.Models;
namespace _2124802010277_LeTuanKiet_CuoiKy.Controllers
{
    public class AssignmentsController : Controller
    {
        DataTiengAnhEntities db = new DataTiengAnhEntities();
        // GET: Assignments
        public ActionResult Index(int id)
        {
            //int id = (int)Session["Id"];
            var x = db.BaiTaps.FirstOrDefault(item => item.IdBaiTap == id);
            List<ChiTietBaiTap> tmp = db.ChiTietBaiTaps.Where(item => item.IdBaiTap == id).ToList();
            ViewBag.BaiTap = x;
            return View(tmp);
        }
        public ActionResult TangLuotXem(int id)
        {
            Session["Id"] = id;
            var x = db.BaiTaps.FirstOrDefault(item => item.IdBaiTap == id);
            if (x != null)
            {
                x.LuotXem += 1;
                db.SaveChanges();
            }
            return RedirectToAction("Index",new { id=id});
        }
        public ActionResult ListAssi(string KeyWork,int pg=1)
        {
            List<BaiTap> ds = db.BaiTaps.ToList();
            if(!String.IsNullOrEmpty(KeyWork))
            {
                int idbt=0;
                if(int.TryParse(KeyWork, out int number))
                {
                    idbt = int.Parse(KeyWork);
                }    
                ds = db.BaiTaps.Where(item => item.TenBaiTap.Contains(KeyWork) || item.IdBaiTap==idbt).ToList();
            }    
            const int pageSize = 20;
            if (pg < 1)
                pg = 1;

            int totalitem = ds.Count();

            var pager = new Pager(totalitem, pg, pageSize);

            int skipPage = (pg - 1) * pageSize;
            List<BaiTap> ds1= ds.OrderBy(item => item.IdBaiTap).Skip(skipPage).Take(pageSize).ToList();
            ViewBag.Pager = pager;
            return View(ds1);
        }
        public ActionResult CreateAssignment()
        {
            if(Session["TaiKhoan"]==null)
            {
                return RedirectToAction("DangNhap","User");
            }
            List<ChiTietBaiTap> tmp = new List<ChiTietBaiTap>(); 
            return View(tmp);
        }
        [HttpPost]
        public ActionResult CreateAssignment(string TenBaiTap, List<ChiTietBaiTap> ListCauHoi)
        {
            string bg = "Các câu hỏi bị lỗi cần sửa lại: ";
            int check = 0;
            for (int i = 0; i < ListCauHoi.Count; i++)
            {
                if (ListCauHoi[i].Ques == null && ListCauHoi[i].A == null
                    && ListCauHoi[i].B == null && ListCauHoi[i].C == null
                    && ListCauHoi[i].D == null && ListCauHoi[i].Ans == null)
                {
                    continue;
                }    
                if (ListCauHoi[i].Ques == null || ListCauHoi[i].A == null 
                    || ListCauHoi[i].B == null || ListCauHoi[i].C == null 
                    || ListCauHoi[i].D == null || ListCauHoi[i].Ans == null 
                    || (ListCauHoi[i].Ans!=ListCauHoi[i].A) && (ListCauHoi[i].Ans != ListCauHoi[i].B) && (ListCauHoi[i].Ans != ListCauHoi[i].C) && (ListCauHoi[i].Ans != ListCauHoi[i].D))
                {
                    bg += ", " + i;
                    check++;
                }
            }
            if(check>0)
            {
                ViewBag.bug = bg;
                ViewBag.TenBaiTap = TenBaiTap;
                return View(ListCauHoi);
            }    
            BaiTap tmp = new BaiTap();
            tmp.TenBaiTap=TenBaiTap;
            NguoiDung Nd = (NguoiDung)Session["TaiKhoan"];
            tmp.TacGia = Nd.MaKH;
            tmp.SoLuotNop = 0;
            tmp.NgayDang = DateTime.Now;
            tmp.DiemTrungBinh = 0;
            tmp.LuotThich = 0;
            tmp.LuotXem = 0;
            db.BaiTaps.Add(tmp);
            db.SaveChanges();
            for (int i = 0; i < ListCauHoi.Count; i++)
            {
                if(ListCauHoi[i].Ques!=null)
                {
                    ChiTietBaiTap bt = ListCauHoi[i];
                    bt.IdBaiTap = tmp.IdBaiTap;
                    db.ChiTietBaiTaps.Add(bt);
                }    
            }
            db.SaveChanges();
            return RedirectToAction("ListAssi");
        }

       /* Show điểm của người dùng*/
       void savePoint(int Acp,int AllQues,int IdBaiTap)
        {
            BaiTap bt = db.BaiTaps.FirstOrDefault(item => item.IdBaiTap == IdBaiTap);
            bt.DiemTrungBinh += (double)Acp / AllQues * 10;
            db.SaveChanges();
        }
       public ActionResult ShowPoint()
        {
            int IdBaiTap = (int)Session["IdBaiTap"];
            if(Session["Diem"]!=null)
            {
                ViewBag.Diem = Session["Diem"];
            }
            if (Session["SoCauHoi"] != null)
            {
                ViewBag.SoCauHoi = Session["SoCauHoi"];
            }
            if (Session["SoCauDung"] != null)
            {
                ViewBag.SoCauDung = Session["SoCauDung"];
            }
            if (Session["SoCauSai"] != null)
            {
                ViewBag.SoCauSai = Session["SoCauSai"];
            }
            if (Session["SoCauChuaLam"] != null)
            {
                ViewBag.SoCauChuaLam = Session["SoCauChuaLam"];
            }
            if (Session["LuaChon"] != null)
            {
                List<string> Chosice = (List<String>)Session["LuaChon"];
                ViewBag.tmp = Chosice;
            }
            List<ChiTietBaiTap> tmp = db.ChiTietBaiTaps.Where(item => item.IdBaiTap == IdBaiTap).ToList();
            return View(tmp);
        }
        public ActionResult SavePoint(int Acp, int Wr, int AllQues, int ChuaLam, string ChosseUser, int IdBaiTap)
        {
            Session["Diem"] = (double)Acp / AllQues * 10;
            Session["SoCauHoi"] = AllQues;
            Session["SoCauDung"] = Acp;
            Session["SoCauSai"] = Wr;
            Session["SoCauChuaLam"] = ChuaLam;
            List<string> Chosice = ChosseUser.Split(',').ToList();
            Session["IdBaiTap"] = IdBaiTap;
            Session["LuaChon"] = Chosice;
        
            BaiTap bt = db.BaiTaps.FirstOrDefault(item => item.IdBaiTap == IdBaiTap);
            double Diem = (double)Acp / AllQues * 10;
            double sum = (double)bt.SoLuotNop * (double)bt.DiemTrungBinh;
            sum += Diem;
            bt.SoLuotNop++;
            bt.DiemTrungBinh =sum/bt.SoLuotNop;
            
            db.SaveChanges();
            return RedirectToAction("ShowPoint");
        }
        public ActionResult test()
        {
            return View();
        }
    }
}

2124802010277_LeTuanKiet_CuoiKy/Views/Assignments/CreateAssignment.cshtml
@model List<_2124802010277_LeTuanKiet_CuoiKy.Models.ChiTietBaiTap>
@{
    ViewBag.Title = "CreateAssignment";
    var bug = ViewBag.bug;
    var TenBaiTap = ViewBag.TenBaiTap;

}
<h4 style="color: red">@bug</h4>
<div style="">
    @using (Html.BeginForm("CreateAssignment", "Assignments", FormMethod.Post, new { style = "" } ))
    {
        <div class="form-group" style="display: flex; flex-direction: column; margin-left: 150px">
            <label class="control-label col-md-2">
                Tên bài tập
            </label>
            <div class="col-md-10">
                <input class="form-control" name="TenBaiTap" value="@TenBaiTap"/>
            </div>
        </div>
        <div class="form-group" style="width: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center; margin: 50px">
            <table width="100%" >
                <!-- Thêm các dòng và cột cho bảng của bạn -->
                <tr>
                    <th>STT</th>
                    <th>Câu hỏi</th>
                    <th>Đáp án A</th>
                    <th>Đáp án B</th>
                    <th>Đáp án C</th>
                    <th>Đáp án D</th>
                    <th>Câu trả lời</th>
                </tr>
                @for (int i = 0; i < 50; i++)
                {
                    if (i < Model.Count)
                    {
                        int tmp = i + 1;
                        <tr>
                            <td>@tmp</td>
                            <td><input type="text" name="ListCauHoi[@i].Ques" value="@Model[i].Ques" style="width: 100%" /></td>
                            <td><input type="text" name="ListCauHoi[@i].A" value="@Model[i].A" style="width: 100%" /></td>
                            <td><input type="text" name="ListCauHoi[@i].B" value="@Model[i].B" style="width: 100%" /></td>
                            <td><input type="text" name="ListCauHoi[@i].C" value="@Model[i].C" style="width: 100%" /></td>
                            <td><input type="text" name="ListCauHoi[@i].D" value="@Model[i].D" style="width: 100%"/></td>
                            <td><input type="text" name="ListCauHoi[@i].Ans" value="@Model[i].Ans" /></td>
                        </tr>
                    }
                    else
                    {
                        int tmp = i + 1;
                        <tr>
                            <td>@tmp</td>
                            <td><input type="text" name="ListCauHoi[@i].Ques" style="width: 100%" /></td>
                            <td><input type="text" name="ListCauHoi[@i].A" style="width: 100%" /></td>
                            <td><input type="text" name="ListCauHoi[@i].B" style="width: 100%" /></td>
                            <td><input type="text" name="ListCauHoi[@i].C" style="width: 100%" /></td>
                            <td><input type="text" name="ListCauHoi[@i].D" style="width: 100%" /></td>
                            <td><input type="text" name="ListCauHoi[@i].Ans"  /></td>
                        </tr>
                    }

                }
            </table>
        </div>
       

        <input type="submit"  class="btn btn-primary btn-rounded" value="Gửi Dữ Liệu" style="float: right"/>
    }


</div>

2124802010277_LeTuanKiet_CuoiKy/Views/Assignments/Index.cshtml
@model List<_2124802010277_LeTuanKiet_CuoiKy.Models.ChiTietBaiTap>
@using Newtonsoft.Json
@{
    ViewBag.Title = "Index";
    _2124802010277_LeTuanKiet_CuoiKy.Models.BaiTap Bt = ViewBag.BaiTap;
    var cauHoiList = Model.Select(cauHoi => new
    {
        cauHoi.IdBaiTap,
        cauHoi.Ques,
        cauHoi.A,
        cauHoi.B,
        cauHoi.C,
        cauHoi.D,
        cauHoi.Ans,
    }).ToList();

    var cauHoiJson = Newtonsoft.Json.JsonConvert.SerializeObject(cauHoiList);
}
<div class="container mt-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-10 col-lg-10">
            <div class="border">
                <div class="question bg-white p-3 border-bottom">
                    <div class="d-flex flex-row justify-content-between align-items-center mcq">
                        <h4>Câu hỏi cho bài kiểm tra</h4><span id="IdQuestion"></span>
                    </div>
                </div>
                <div class="question bg-white p-3 border-bottom">
                    <div class="d-flex flex-row align-items-center question-title">
                        <h3 class="text-danger">Q.</h3>
                        <h5 class="mt-1 ml-2" id="Question"></h5>
                    </div>
                    <div style="display: flex; flex-direction: row; align-items: center; justify-content: center">
                        <div class="ans ml-2">
                            <label class="radio">
                                <input type="radio" name="ans" id="valuA" onclick="ChooseUser()"> <span id="ansA"></span>
                            </label>
                        </div>
                        <div class="ans ml-2">
                            <label class="radio">
                                <input type="radio" name="ans" id="valuB" onclick="ChooseUser()"> <span id="ansB"></span>
                            </label>
                        </div>
                        <div class="ans ml-2">
                            <label class="radio">
                                <input type="radio" name="ans" id="valuC" onclick="ChooseUser()"> <span id="ansC"></span>
                            </label>
                        </div>
                        <div class="ans ml-2">
                            <label class="radio">
                                <input type="radio" name="ans" id="valuD" onclick="ChooseUser()"> <span id="ansD"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="d-flex flex-row justify-content-between align-items-center p-3 bg-white">
                    <button class="btn btn-primary d-flex align-items-center btn-danger" type="button" onclick="getSelectAnswerPrevious()">
                        <i class="fa fa-angle-left mt-1 mr-1"></i>&nbsp;previous
                    </button>
                    <button class="btn btn-primary border-success align-items-center btn-success" type="button" onclick="getSelectedAnswerNext()">
                        Next<i class="fa fa-angle-right ml-2"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<button onclick="End()" style="height: 50px; width: 150px; background-color: blue; float: right">
    Nộp bài
</button>
<div class="container">
    <div class="row" style="align-items: center; justify-content: center">
        <div class="four col-md-3">
            <div class="counter-box colored">
                <i class="fa fa-thumbs-o-up"></i>
                <span class="counter">@Bt.LuotThich</span>
                <p>Lượt thích</p>
            </div>
        </div>
        <div class="four col-md-3">
            <div class="counter-box">
                <i class="fa fa-group"></i>
                <span class="counter">@Bt.SoLuotNop</span>
                <p>Lượt làm bài</p>
            </div>
        </div>
        <div class="four col-md-3">
            <div class="counter-box" style="height: 209px; display: flex; flex-direction: column; align-items: center; justify-content: center">
                <span class="counter">@Bt.DiemTrungBinh</span>
                <p>Điểm trung bình</p>
            </div>
        </div>
    </div>
</div>
<script>
    var id = 0;

    var Lquestion = @Html.Raw(cauHoiJson);
    console.log(Lquestion);
        var AnsUser = [];
    var Point = [];
    console.log(Lquestion);

    @* set data cho html start *@
    var Q = document.getElementById('Question').innerHTML = Lquestion[0].Ques;
    var x = document.getElementById('ansA').innerHTML = Lquestion[0].A;
    var y = document.getElementById('valuA').value = Lquestion[0].A;

    var x1 = document.getElementById('ansB').innerHTML = Lquestion[0].B;
    var y1 = document.getElementById('valuB').value = Lquestion[0].B;

    var x2 = document.getElementById('ansC').innerHTML = Lquestion[0].C;
    var y2 = document.getElementById('valuC').value = Lquestion[0].C;

    var x3 = document.getElementById('ansD').innerHTML = Lquestion[0].D;
    var y3 = document.getElementById('valuD').value = Lquestion[0].D;

    var idQ = document.getElementById('IdQuestion').innerHTML = 1 + " of " + Lquestion.length;
    @*set data cho html end*@

    @*xử lý nút next và previous start*@
    function getSelectedAnswerNext() {
        var selectedAnswer = document.querySelector('input[name="ans"]:checked');
        if (selectedAnswer) {
            selectedAnswer.checked = false;
        }

        //Xóa background khi bấm nút tiếp theo
        var labels = document.querySelectorAll('.radio');

        // Thay đổi nền màu của các thẻ label thành màu trắng
        for (var i = 0; i < labels.length; i++) {
            labels[i].style.backgroundColor = 'white';
            //console.log(labels[i]);
        }
        //Xét lại câu hỏi
        if (id == Lquestion.length-1)
            id = Lquestion.length-1;
        else
            id += 1;

        //console.log(id);
        var Q = document.getElementById('Question').innerHTML = Lquestion[id].Ques;
        var x = document.getElementById('ansA').innerHTML = Lquestion[id].A;
        var y = document.getElementById('valuA').value = Lquestion[id].A;
        var x1 = document.getElementById('ansB').innerHTML = Lquestion[id].B;
        var y1 = document.getElementById('valuB').value = Lquestion[id].B;
        var x2 = document.getElementById('ansC').innerHTML = Lquestion[id].C;
        var y2 = document.getElementById('valuC').value = Lquestion[id].C;
        var x3 = document.getElementById('ansD').innerHTML = Lquestion[id].D;
        var y3 = document.getElementById('valuD').value = Lquestion[id].D;
        var idQ = document.getElementById('IdQuestion').innerHTML = id + 1 + " of " + Lquestion.length;
        if (AnsUser[id] != null) {
            var H = document.getElementById(AnsUser[id]);
            H.checked = true;
        }

    }
    function getSelectAnswerPrevious() {
        var selectedAnswer = document.querySelector('input[name="ans"]:checked');
        if (selectedAnswer) {
            selectedAnswer.checked = false;
        }

        //Xóa background khi bấm nút tiếp theo
        var labels = document.querySelectorAll('.radio');

        // Thay đổi nền màu của các thẻ label thành màu trắng
        for (var i = 0; i < labels.length; i++) {
            labels[i].style.backgroundColor = 'white';
            //console.log(labels[i]);
        }
        //Xét lại câu hỏi
        if (id == 0)
            id = 0;
        else
            id -= 1;
        var Q = document.getElementById('Question').innerHTML = Lquestion[id].Ques;
        var x = document.getElementById('ansA').innerHTML = Lquestion[id].A;
        var y = document.getElementById('valuA').value = Lquestion[id].A;
        var x1 = document.getElementById('ansB').innerHTML = Lquestion[id].B;
        var y1 = document.getElementById('valuB').value = Lquestion[id].B;
        var x2 = document.getElementById('ansC').innerHTML = Lquestion[id].C;
        var y2 = document.getElementById('valuC').value = Lquestion[id].C;
        var x3 = document.getElementById('ansD').innerHTML = Lquestion[id].D;
        var y3 = document.getElementById('valuD').value = Lquestion[id].D;
        var idQ = document.getElementById('IdQuestion').innerHTML = id + 1 + " of " + Lquestion.length;
        if (AnsUser[id] != null) {
            var H = document.getElementById(AnsUser[id]);
            H.checked = true;
        }
    }
    @* xử lý nút next và previous end *@

    function ChooseUser() {
        var selectedAnswer = document.querySelector('input[name="ans"]:checked');
        if (selectedAnswer) {
            AnsUser[id] = selectedAnswer.id;
            Point[id] = selectedAnswer.value;
        }
    }

    function End() {
        var pointUser = 0;
        var Wr = 0;
        var ChuaLam = 0;
        for (let i = 0; i < Lquestion.length; i++) {
            if (Point[i] != null && Point[i] == Lquestion[i].Ans) {
                pointUser++;
            }
            if (Point[i] != null && Point[i] != Lquestion[i].Ans) {
                //console.log(Point[i] + ' ' + Lquestion[i].DapAnDung);
                Wr++;
                console.log(Point[i] + ' ' + Lquestion[i].Ans);
            }
            if (Point[i] == null)
                ChuaLam++;
        }
        window.location.href = '/Assignments/SavePoint?Acp=' + pointUser + '&Wr=' + Wr + '&AllQues=' + Lquestion.length + '&ChuaLam=' + ChuaLam + '&ChosseUser=' + Point + '&IdBaiTap=' + Lquestion[0].IdBaiTap;
        console.log(pointUser);
        //console.log('/Assignments/ShowPoint?Acp=' + pointUser + '&Wr=' + Wr + '&AllQues=' + Lquestion.length + '&ChuaLam=' + ChuaLam + '&ChosseUser=' + Point + '&IdBaiTap=' + Lquestion[0].IdBaiTap);
    }
</script>

2124802010277_LeTuanKiet_CuoiKy/Views/Assignments/ListAssi.cshtml
@model List<_2124802010277_LeTuanKiet_CuoiKy.Models.BaiTap>
@using _2124802010277_LeTuanKiet_CuoiKy.Models
@{
    ViewBag.Title = "ListAssi";
    _2124802010277_LeTuanKiet_CuoiKy.Models.NguoiDung x = new _2124802010277_LeTuanKiet_CuoiKy.Models.NguoiDung();
    DataTiengAnhEntities db = new DataTiengAnhEntities();


    _2124802010277_LeTuanKiet_CuoiKy.Models.Pager p = new _2124802010277_LeTuanKiet_CuoiKy.Models.Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        p = ViewBag.Pager;
        pageNo = p.CurrentPage;
    }
}
<div class="ContainerExams">
    <div style="display: flex; flex-direction: row-reverse; margin-bottom: 15px">
        <a href="@Url.Action("CreateAssignment","Assignments")" class="btn btn-outline-primary" style="margin-left: 20px; height: 45px; display: flex; align-items: center; justify-content: center">
            Đăng bài tập
        </a>
        <form class="input-group" style="display: flex; flex-direction: row-reverse">
            <button type="submit" class="btn btn-outline-primary" data-mdb-ripple-init
                    style="height: 45px; border-radius: 5px">
                search
            </button>
            <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" name="KeyWork" style="max-width: 30%" />
        </form>
    </div>
    
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Tên Bài</th>
                <th scope="col">Ngày Đăng</th>
                <th scope="col">Tên tác giả</th>
                <th scope="col" style="text-align: center">Điểm trung bình</th>
                <th scope="col" style="text-align: center">Số lượt nộp bài</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                x = db.NguoiDungs.FirstOrDefault(n => n.MaKH == item.TacGia);
                <tr>
                    <th scope="row"><a href="@Url.Action("TangLuotXem","Assignments", new { id=item.IdBaiTap})">@item.TenBaiTap</a></th>
                    <td class="DetailExams">@string.Format("{0:dd/MM/yyyy}", item.NgayDang)</td>
                    <td class="DetailExams">@x.HoTenKH</td>
                    <td class="DetailExams" style="text-align: center">@item.DiemTrungBinh</td>
                    <td class="DetailExams" style="text-align: center">@item.SoLuotNop</td>
                </tr>
            }
        </tbody>
    </table>
    <div class="container">
        <ul class="pagination justify-content-end">
            @for (int i = p.StartPage; i <= p.EndPage; i++)
            {
                <li class="page-item @(i==p.CurrentPage ? "active" : "")">
                    <a class="page-link" href="~/Assignments/ListAssi?pg=@i">@i</a>
                </li>
            }
        </ul>
    </div>
</div>
<script>

</script>

2124802010277_LeTuanKiet_CuoiKy/Views/Assignments/ShowPoint.cshtml
@model IEnumerable<_2124802010277_LeTuanKiet_CuoiKy.Models.ChiTietBaiTap>
@{
    ViewBag.Title = "ShowPoint";
   
    var Chosse = ViewBag.tmp;
    List<string> Chosse1 = Chosse;
}
<div class="ContainerWait">
    <div class="wrapper" style="margin-top: 50px">
        <!-- <img src="./pngtree-alarm-clock-cartoon-cartoon-cartoon-alarm-clock-png-image_479554.jpg" alt="clock">
        <h1 id="time">00:00:00 PM</h1> -->
        <div class="card text-center">
            <div class="card-header">Tổng điểm của bạn là @ViewBag.Diem</div>
            <div class="card-body">
                <h5 class="card-title">Tổng số câu hỏi: @ViewBag.SoCauHoi</h5>
                <p class="card-text">Số câu đúng: @ViewBag.SoCauDung</p>
                <p class="card-text">Số câu sai: @ViewBag.SoCauSai</p>
                <p class="card-text">Số câu Chưa làm: @ViewBag.SoCauChuaLam</p>
            </div>
            <div class="card-footer text-muted">2 days ago</div>
        </div>
    </div>
    <div style="margin-top: 20px; display: flex; flex-direction: column; padding-bottom: 50px">
        <h2>Đáp án</h2>
        <table class="table align-middle mb-0 bg-white" style="margin-bottom: 10px">
            <thead class="bg-light">
                <tr>
                    <th>Câu hỏi</th>
                    <th>Đáp án A</th>
                    <th>Đáp án B</th>
                    <th>Đáp án C</th>
                    <th>Đáp án D</th>
                    <th>Đáp án Đúng</th>
                    <th>Đáp án Bạn chọn</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count(); i++)
                {
                    var item = Model.ElementAt(i);
                    <tr>
                        <td>
                            <div class="d-flex align-items-center">
                                <div class="ms-3">
                                    <p class="fw-bold mb-1">@item.Ques</p>
                                </div>
                            </div>
                        </td>
                        <td>
                            <p class="fw-normal mb-1">@item.A</p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1">@item.B</p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1">@item.C</p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1">@item.D</p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1">@item.Ans</p>
                        </td>
                        @if (i < Chosse1.Count() && Chosse1[i] != "")
                        {
                            <td>@Chosse1[i]</td>
                        }
                        else
                        {
                            <td>Chưa làm </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

2124802010277_LeTuanKiet_CuoiKy/Views/Assignments/test.cshtml
@model IEnumerable<_2124802010277_LeTuanKiet_CuoiKy.Models.ChiTietBaiTap>
<div>assf</div>